Step1/2:

Adds the dataset and removes NaN values and copies the dataframe for datachecking and confirmation

In [1]:
import pandas as pd
import numpy as np
import sklearn.datasets 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
sca = StandardScaler()
enc = LabelEncoder()
oenc = OneHotEncoder()

In [2]:
df = pd.read_csv("Medical.csv")

In [3]:
df=df.replace(r'^\s*$', np.nan, regex=True)
df.dropna(inplace=True,axis=0)
df

PatientId  AppointmentID Gender          ScheduledDay  \
0       2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1       5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2       4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3       8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4       8.841186e+12        5642494      F  2016-04-29T16:07:23Z   
...              ...            ...    ...                   ...   
110522  2.572134e+12        5651768      F  2016-05-03T09:15:35Z   
110523  3.596266e+12        5650093      F  2016-05-03T07:27:33Z   
110524  1.557663e+13        5630692      F  2016-04-27T16:03:52Z   
110525  9.213493e+13        5630323      F  2016-04-27T15:09:23Z   
110526  3.775115e+14        5629448      F  2016-04-27T13:30:56Z   

              AppointmentDay  Age      Neighbourhood  Scholarship  \
0       2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0   
1       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   
2       2016-04-29T00:00:00Z   62      MATA DA PRAIA            0   
3       2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0   
4       2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   
...                      ...  ...                ...          ...   
110522  2016-06-07T00:00:00Z   56        MARIA ORTIZ            0   
110523  2016-06-07T00:00:00Z   51        MARIA ORTIZ            0   
110524  2016-06-07T00:00:00Z   21        MARIA ORTIZ            0   
110525  2016-06-07T00:00:00Z   38        MARIA ORTIZ            0   
110526  2016-06-07T00:00:00Z   54        MARIA ORTIZ            0   

        Hipertension  Diabetes  Alcoholism  Handcap  SMS_received No-show  
0                  1         0           0        0             0      No  
1                  0         0           0        0             0      No  
2                  0         0           0        0             0      No  
3                  0         0           0        0             0      No  
4                  1         1           0        0             0      No  
...              ...       ...         ...      ...           ...     ...  
110522             0         0           0        0             1      No  
110523             0         0           0        0             1      No  
110524             0         0           0        0             1      No  
110525             0         0           0        0             1      No  
110526             0         0           0        0             1      No  

[110527 rows x 14 columns]

In [4]:
mdf= df.copy()

Step 3:

Extracts the features

In [5]:
mdf=mdf.drop(columns=['PatientId',"AppointmentID","ScheduledDay","AppointmentDay","Neighbourhood"])

In [6]:
mdf

Gender  Age  Scholarship  Hipertension  Diabetes  Alcoholism  Handcap  \
0           F   62            0             1         0           0        0   
1           M   56            0             0         0           0        0   
2           F   62            0             0         0           0        0   
3           F    8            0             0         0           0        0   
4           F   56            0             1         1           0        0   
...       ...  ...          ...           ...       ...         ...      ...   
110522      F   56            0             0         0           0        0   
110523      F   51            0             0         0           0        0   
110524      F   21            0             0         0           0        0   
110525      F   38            0             0         0           0        0   
110526      F   54            0             0         0           0        0   

        SMS_received No-show  
0                  0      No  
1                  0      No  
2                  0      No  
3                  0      No  
4                  0      No  
...              ...     ...  
110522             1      No  
110523             1      No  
110524             1      No  
110525             1      No  
110526             1      No  

[110527 rows x 9 columns]

Step 4:

Encodes the features that are not integers

In [16]:
No_show= mdf.iloc[:, 8]

mdf['Gender']= enc.fit_transform(mdf.Gender.values)
mdf['No-show']= enc.fit_transform(No_show.values)

In [17]:
mdf

Gender  Age  Scholarship  Hipertension  Diabetes  Alcoholism  Handcap  \
0            0   62            0             1         0           0        0   
1            1   56            0             0         0           0        0   
2            0   62            0             0         0           0        0   
3            0    8            0             0         0           0        0   
4            0   56            0             1         1           0        0   
...        ...  ...          ...           ...       ...         ...      ...   
110522       0   56            0             0         0           0        0   
110523       0   51            0             0         0           0        0   
110524       0   21            0             0         0           0        0   
110525       0   38            0             0         0           0        0   
110526       0   54            0             0         0           0        0   

        SMS_received  No-show  
0                  0        0  
1                  0        0  
2                  0        0  
3                  0        0  
4                  0        0  
...              ...      ...  
110522             1        0  
110523             1        0  
110524             1        0  
110525             1        0  
110526             1        0  

[110527 rows x 9 columns]

Step 5:

Splits the data

In [28]:
X= mdf.iloc[:, 0:8].values
y=mdf.iloc[:, 8].values

In [31]:
from sklearn.model_selection import train_test_split
train_ratio = 0.80
validation_ratio = 0.10
test_ratio = 0.10

# train is now 80% of the entire data set
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=1 - train_ratio)

# test is now 10% of the initial data set
# validation is now 10% of the initial data set
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=test_ratio/(test_ratio + validation_ratio)) 

print(x_train, x_val, x_test)

[[ 0  0  0 ...  0  0  0]
 [ 1 75  0 ...  0  0  0]
 [ 0 29  0 ...  0  0  0]
 ...
 [ 0 52  0 ...  0  0  1]
 [ 0 88  0 ...  0  0  1]
 [ 1 26  0 ...  0  0  0]] [[ 0 49  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 1 55  0 ...  0  0  0]
 ...
 [ 0 16  0 ...  0  0  0]
 [ 1 65  0 ...  0  0  0]
 [ 1 11  0 ...  0  0  0]] [[ 0 24  0 ...  0  0  0]
 [ 0 70  0 ...  0  0  0]
 [ 1 32  0 ...  0  0  1]
 ...
 [ 1 16  0 ...  0  0  0]
 [ 0 15  0 ...  0  0  0]
 [ 0 56  0 ...  0  0  0]]


Step 6.1:

Performs DecisionTreeClassifier and ends up with a decent result of 79$ on both the validation and test scores and prints them off

In [56]:
from sklearn.tree import DecisionTreeClassifier
Dmodel = DecisionTreeClassifier(criterion="entropy" , splitter='best')
Dmodel.fit(x_train, y_train)
D_pred = Dmodel.predict(x_test)
Dscore = Dmodel.score(x_val,y_val)
from sklearn.metrics import recall_score
print('Score using the test data: '+ str(recall_score(y_test, D_pred,  average='weighted')))
print('Score using the validation data: ',Dscore)

Score using the test data: 0.7939021080249706
Score using the validation data:  0.7932687958020447


Step 6.2:

Prints the confusion matrix and classification report

In [57]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test, D_pred))
print(classification_report(y_test, D_pred))

[[8737   57]
 [2221   38]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.88      8794
           1       0.40      0.02      0.03      2259

    accuracy                           0.79     11053
   macro avg       0.60      0.51      0.46     11053
weighted avg       0.72      0.79      0.71     11053



Step 7:

Performs a RandomForestClassifier and ends up with a very jank variant where the test data never breaches 2% but the validation is always 79% so honestly I would prefer to use a Decision Tree Classifier in this case

In [59]:
from sklearn.ensemble import RandomForestClassifier 
Rmodel = RandomForestClassifier(n_estimators=10, criterion='entropy')
Rmodel.fit(x_train, y_train)
    
R_pred = Rmodel.predict(x_test)
    
Rscore = Rmodel.score(x_val,y_val)
    
from sklearn.metrics import recall_score
print('Score using the test data: ' + str(recall_score(y_test, R_pred)))
print('Score using the validation data: ',Rscore)

Score using the test data: 0.01859229747675963
Score using the validation data:  0.7918212250067855
